# Generated by Django 3.2.7 on 2021-09-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depts', '0001_initial'),
        ('students', '0004_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_students', to='depts.department'),
        ),
    ]
